### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by ObsidianChief** [MrSquirrelyNet/mace-minecraft#10]
Will this ever get updates again? Or is it KIA?

**Comment by MrSquirrely** [comment]
Hmm. I'm not going to lie I kind of forgot about this. Ah, the answer is yes I will get it updated. The slight problem I have is decoding and re-coding all of his old code. I started doing this when I knew little about C# but now that I have gotten a lot better I'm coming back to this! (So what took me like 3 hours back then just took me ~an hour to do)

**Comment by MrSquirrely** [comment]
Well sorry, I have seemed to have lied to you. Doing some research to try and update this the library that was used to modify the words is not updated, so I won't be updating this as I have no interest in updating the library as well.
